### ISSUE TITLE
Dependency memcached-northscale doesn't work on MRI 1.9.3-p0.

### ISSUE THREAD

**Issue by leehambley** [benschwarz/amnesia#3]
Not sure why I'm filing the bug here, simply to sound it out, I guess.

Under 1.9.3 the memcached-northscale Gem doesn't work, (compile errors owing to missing symbols here…) therefore amnesia doesn't work.

What level of effort do you imagine is required to take a different memcached driver?

**Update:** Having taken a moment to look [at the source](https://github.com/benschwarz/amnesia/blob/master/lib/amnesia/host.rb#L31). I imagine you can expect a fork/pull soon enough

**Comment by glaszig** [comment]
1.9.3 is eol. should be closed as well.
