### ISSUE TITLE
Call to String#sum is causing weird results

### ISSUE THREAD

**Issue by ghiculescu** [benschwarz/amnesia#8]
Amnesia kept giving me output like this, which didn't feel right (note I have tweaked the views slightly, but hadn't changed the non-view code prior):

![screen shot 2013-07-31 at 12 31 56 am](https://f.cloud.github.com/assets/509837/879267/cde9a1c2-f924-11e2-8515-74567b5e4a63.png)

So I dove into the code and made [this change](https://github.com/ghiculescu/amnesia/commit/1bf7b3c46da71815a0ae0bb82ad9a0e88fc37811#lib/amnesia/host.rb)

And now the results look more like this:

![screen shot 2013-07-31 at 12 32 47 am](https://f.cloud.github.com/assets/509837/879277/ee841840-f924-11e2-8457-04582278382e.png)

Which feels much more correct. [String#sum](http://www.ruby-doc.org/core-1.9.3/String.html#method-i-sum) doesn't seem to do anything helpful in this context, so I'm not sure why it was being included. Please let me know if I've overlooked something! Otherwise I'll be happy to make a pull request.

**Comment by glaszig** [comment]
resolved with #11. can be closed.
